apiVersion: v1
kind: Service
metadata:
  labels:
    app: myappspa
  name: myappspa
spec:
  selector:
    app: myapp
    component: spa
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http