apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-todo
  labels:
    app: {{ template "name" . }}-todo
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.apptodo.service.type }}
  ports:
    - port: {{ .Values.apptodo.service.externalPort }}
      targetPort: {{ .Values.apptodo.service.internalPort }}
      protocol: TCP
      name: {{ .Values.apptodo.service.name }}
  selector:
    app: {{ template "name" . }}-todo
    release: {{ .Release.Name }}
